"""category added

Revision ID: 318549c3dc0d
Revises: c48c85fd6ee5
Create Date: 2022-05-10 14:15:35.588548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318549c3dc0d'
down_revision = 'c48c85fd6ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('category', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'category')
    # ### end Alembic commands ###
